### ISSUE TITLE
Todo: more snippets

### ISSUE THREAD

**Issue by melanieseltzer** [melanieseltzer/es6-all-the-things#1]
- [x] Promises
- [x] Map
- [ ] Sets
- [x] Fat arrows: returning objects
- [x] Nested object destructuring
- [x] Object destructuring renaming 
- [x] Skipping values in array destructing

Any others?

**Comment by askhat** [comment]
Optional prop declarations might be included as well

```javascript
{
  ...someCondtion && { prop: 'value' }
}
```

**Comment by melanieseltzer** [comment]
@askhat Do you have more info about that I could read up on?

**Comment by askhat** [comment]
I made a pull request, hope it'll clear things out
